### ISSUE TITLE
Dependency declared on Apache HttpClient5 but implementation still using 4

### ISSUE THREAD

**Issue by brenuart** [okta/okta-commons-java#126]
Hey guys,
First of all, a big thank you for the Java SDK. Definitely a very nice library. Great job!

I noticed that `okta-http-httpclient` is declaring a direct dependency on `org.apache.httpcomponents.client5:httpclient5` since version 1.3.1 (introduced by [this](https://github.com/okta/okta-commons-java/commit/bdfef9a99620baf8ae99f47ac095c7c967a098be) change). 

Upon examining the code, it becomes evident that the library is not using Apache client version 5 as anticipated, but rather it is still reliant on version 4. It is important to note that these two versions, 4 and 5, are separate libraries with distinct Java package names. Migrating from version 4 to version 5 necessitates more than just updating the version number in the pom file; it also entails modifying the code itself.

In my opinion, there are multiple choices available:
- Revert the changes made and return the dependency to HttpClient 4.
- Adjust the code to effectively use HttpClient 5.
- Develop a separate implementation to provide HttpClient 5 as an additional option alongside OkHttp and HttpClient 4.

/bertrand

**Comment by brenuart** [comment]
Any feedback?

**Comment by arvindkrishnakumar-okta** [comment]
@brenuart Thanks for the feedback, I'll get this worked out in a PR soon.
