### ISSUE TITLE
Content-length header is not set, leading to HTTP 411 error

### ISSUE THREAD

**Issue by kaichunlin** [okta/okta-commons-java#52]
The `com.okta.sdk:okta-sdk-okhttp` library our app uses requires `com.okta.commons:okta-http-api`.
When `com.okta.authn.sdk.client.AuthenticationClient.authenticate` is called, `com.okta.commons.http.okhttp.InputStreamRequestBody` is used to provide the request body for the POST HTTP call. However, `InputStreamRequestBody` does not override the default `RequestBody.contentLength()` method, which always returns -1. This has the effect of OkHttp stripping out any manually set Content-length header and leaves it unset, causing server to return HTTP 411.

The fix is to override `public long contentLength()` to return the correct value.

**Comment by bdemers** [comment]
Thanks for the report @kaichunlin !

Just to follow up, which version of the `okta-auth-java` library are you using, and which version of the `okta-sdk-okhttp` lib?

**Comment by kaichunlin** [comment]
@bdemers 
We are using `com.okta.sdk:okta-sdk-okhttp:4.0.0` that depends on `com.okta.commons:okta-http-okhttp:1.2.5`, which is the library with the `InputStreamRequestBody` class.

**Comment by arvindkrishnakumar-okta** [comment]
@kaichunlin can you post a complete redacted wire trace of the API call for this case?

**Comment by kaichunlin** [comment]
@arvindkrishnakumar-okta I can provide the curl for the requests with certain headers removed:
`curl -H 'Host: redacted.lululemon.com' -H 'accept: application/json' -H 'user-agent: lululemon/3.2.15.dev-DEBUG (redacted)' -H 'content-type: application/json' --data-binary '{"relayState":null,"password":"pass","username":"username"}' --compressed 'https://redacted.lululemon.com/api/v1/authn'`

We observed the exact same behaviour before and after updating the okta libraries we use, before:
```
    implementation 'com.okta.android:oidc-androidx:1.0.17'
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
    }
    implementation 'com.okta.sdk:okta-sdk-okhttp:1.5.2'
```
after:
```
    implementation 'com.okta.android:oidc-androidx:1.0.18'
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:2.0.2'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:2.0.2') {
        exclude group: 'org.bouncycastle'
    }
    implementation 'com.okta.sdk:okta-sdk-okhttp:4.0.0'
```

When you say you had no luck reproducing this issue, did you mean you didn't see any 411 errors, or that all your API calls have `content-length` set?

**Comment by arvindkrishnakumar-okta** [comment]
@kaichunlin Are the HTTP 411 errors coming from Okta server or your company's server?

**Comment by kaichunlin** [comment]
@arvindkrishnakumar-okta neither, it's blocked by Akamai

**Comment by bdemers** [comment]
@kaichunlin is Akamai proxying requests to Okta?
Your client code -> Akamai -> Okta?

Is it a regular HTTP proxy?

(just trying to understand who else might be seeing this issue)

It should be fixed #53 too 😄

**Comment by kaichunlin** [comment]
@bdemers unfortunately I work solely on the app end and is not privy to that info

**Comment by kaichunlin** [comment]
@bdemers is there an ETA on when the next release will be? Thanks

**Comment by arvindkrishnakumar-okta** [comment]
@kaichunlin Stay tuned, I'll get the release out this week.

**Comment by arvindkrishnakumar-okta** [comment]
@kaichunlin I just released v1.2.6 and it should be available in Maven Central in ~2-3 hours from now.

**Comment by kaichunlin** [comment]
@arvindkrishnakumar-okta Thanks! Unfortunately I cannot test it atm as there's some issue with Akamai and Okta in our stage environment.
On another note, as mentioned when opening this ticket, this library is used by `com.okta.sdk:okta-sdk-okhttp` and not directly by our app. Is it possible to have `com.okta.sdk:okta-sdk-okhttp` updated to use the latest version? Otherwise in gradle I need to add this to force usage of the newer version:
```
configurations.all {
        resolutionStrategy.force 'com.okta.commons:okta-http-okhttp:1.2.6'
}
```

**Comment by arvindkrishnakumar-okta** [comment]
@kaichunlin you can use v4.1.0 of okta-sdk-okhttp that contains includes v1.2.6 of okta-commons-java lib.

**Comment by kaichunlin** [comment]
@arvindkrishnakumar-okta everything checks out now, thank you!
