### ISSUE TITLE
Allow customizing the OkHttp instance

### ISSUE THREAD

**Issue by ansman** [okta/okta-commons-java#59]
In a constrained environment such as Android there is great value in only creating a single OkHttp instance since it consumes a large amount of system resources (most noticeably threads).

It would be great if there was a way to provide a base OkHttp instance to the request executor that is uses as a base. The request executor can create a copy of OkHttp to customize things like timeouts etc.

**Comment by ansman** [comment]
I'm happy to open a PR if I can get some pointers on how this is best done. I considered hooking into `HttpClientConfiguration` but it seems that it's created in some places without the consumer being able to configure it.

**Comment by JayNewstrom** [comment]
We don't currently allow customizing the OkHttp instance. The best way to customize it right now is to copy/paste the code in this repo, and customize it to your liking. It's very small (2 classes).

https://github.com/okta/okta-commons-java/tree/master/http/okhttp/src/main/java/com/okta/commons/http/okhttp

**Comment by JayNewstrom** [comment]
We use `ServiceLoader`, https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html to create this. Service loaders aren't capable of taking arguments (such as OkHttp). Seems like the logical thing to do would to be to provide yet another ServiceLoader for the OkHttp instance, and optionally use that in the implementation. But I'm open to other thoughts. 

cc @arvindkrishnakumar-okta do you have any thoughts here?

**Comment by ansman** [comment]
It seems that `HttpClientConfiguration` has support for storing arbitrary values to keys, I was thinking that it could be used to pass values to the OkHttp factory.

**Comment by JayNewstrom** [comment]
Both options seem reasonable. Let's wait for some feedback from @arvindkrishnakumar-okta to see what he thinks.

**Comment by bdemers** [comment]
I'm guessing we could add a new constructor to
https://github.com/okta/okta-commons-java/blob/master/http/okhttp/src/main/java/com/okta/commons/http/okhttp/OkHttpRequestExecutorFactory.java

**NOTE:** we would still need the default constructor for the `ServiceLoader` functionality 

🤔 and probably the delay the creation of the `OkHttpRequestExecutor` until create is called, so may something like:

```java
@AutoService(RequestExecutorFactory.class)
public class OkHttpRequestExecutorFactory implements RequestExecutorFactory {

   final private OkHttpClient okHttpClient;

    public OkHttpRequestExecutorFactory() {
        this(null);
    }

    public OkHttpRequestExecutorFactory(OkHttpClient okHttpClient) {
        this.okHttpClient = okHttpClient;
    }

    @Override
    public RequestExecutor create(HttpClientConfiguration clientConfiguration) {
        return new RetryRequestExecutor(clientConfiguration, 
            okHttpClient == null ? new OkHttpRequestExecutor(clientConfiguration) : new OkHttpRequestExecutor(clientConfiguration, okHttpClient));
    }
}
```

Probably cleaned up a little, that probably isn't the most legible code, but hopefully, it illustrates the idea

**Comment by JayNewstrom** [comment]
@ansman You mentioned you'd be interested in sending a PR, I think the direction from @bdemers is going to be the best route forward. If you want to send a PR, feel free. Otherwise I can make the update too.

**Comment by JayNewstrom** [comment]
I created an internal tracking issue for this: OKTA-428340

**Comment by ansman** [comment]
Sharing a client can have down sides if the consumer has added things like interceptors, caching etc. The risk can be minimized by just manually copying over the expensive things such as the thread pool. But if the user is advanced enough to do this then they hopefully know the implications of sharing the instance.

**Comment by JayNewstrom** [comment]
https://github.com/okta/okta-commons-java/pull/60

**Comment by JayNewstrom** [comment]
Once released, this can be used by subclassing the `OkHttpRequestExecutorFactory`, and adding a service loader pointing to your subclass.

In your subclass, you'll need to instantiate/locate your OkHttpClient instance, and pass it to the `super` constructor.

**Comment by JayNewstrom** [comment]
@ansman This was released as 1.2.8! https://github.com/okta/okta-commons-java/releases/tag/okta-commons-root-1.2.8

**Comment by ansman** [comment]
Damn, crazy fast turn around time 🤯 
Thank you so much!

**Comment by arvindkrishnakumar-okta** [comment]
@ansman allow 1-2 hours for the artifact to appear in maven central repo.
