### ISSUE TITLE
okhttp throws NoSuchMethodError when calling /api/v1/users/invalid-user-id

### ISSUE THREAD

**Issue by rodriguesgm** [okta/okta-commons-java#74]
Hi

**Description**
I'm using [okta-sdk-java](https://github.com/okta/okta-sdk-java) with `okta-sdk-okhttp` to request okta api. When using the sdk to get a specific user but with an invalid/nonexistent id, which will call the endpoint `/api/v1/users/invalid-user-id`, it throws a `NoSuchMethodError`.
I though it was because I was passing an invalid string as id but I can pass an id with the same okta id pattern, just replacing some digit to simulate the invalid user id and I get the same error

Before I was using `okta-sdk-httpclient` which throws `com.okta.sdk.resource.ResourceException`, so I was expecting the same behaviour.

The same happens with getting a specific group and I guess with the others entities too.

Any help on this?

![image](https://user-images.githubusercontent.com/10141664/158244248-a4958856-34f4-439a-849d-e528c3da2d63.png)

**Config**

In my pom.xml

```
       <okta.sdk.version>8.1.0</okta.sdk.version>

        ...
        
       <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-api</artifactId>
            <version>${okta.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-impl</artifactId>
            <version>${okta.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.okta.sdk</groupId>
            <artifactId>okta-sdk-okhttp</artifactId>
            <version>${okta.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <version>1.0.1</version>
        </dependency>
```

**Comment by rodriguesgm** [comment]
Hi @arvindkrishnakumar-okta thanks for the reply

Yes, like I said I was using `okta-sdk-httpclient` which was working fine. But I'm trying to integrate with [zalando/logbook ](https://github.com/zalando/logbook#http-client) library, which does support `http-client`. But unfortunately I couldn't find a way to plug it into okta-sdk-java.

Using the `okta-sdk-okhttp` it was possible, since logbook also support [okhttp](https://github.com/zalando/logbook#okhttp-v3x). That's why I'm trying to use it.

**Comment by arvindkrishnakumar-okta** [comment]
@rodriguesgm thanks for clarifying this. Would you be able to create a minimal sample project in GitHub that can help me reproduce this issue quickly?

**Comment by rodriguesgm** [comment]
Hey @arvindkrishnakumar-okta 
in the process of creating a sample project I saw that I couldn't reproduce the error, so I suspected that it was the integration with zalando/logbook. I saw I was using the version `3.14.9` of `com.squareup.okhttp3:okhttp` in both projects, the sample and the real one with zalando. So I guess zalando lib has some issues with the old version of okhttp3. After upgrading to `4.9.3` it fixed the issue. 

So, it's fine now, you can close this issue.
Thanks a lot for the help
